name: Frontend React

on:
  push:
    branches: [ master ]
    paths:
      - 'First_test/frontend_react/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'First_test/frontend_react/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: Install packages
      run: npm install
      working-directory: First_test/frontend_react/
    - name: Build app
      run: npm run build
      # run: CI=false npm run build  # decomment this line and comment the previous one to ignore build warnings
      working-directory: First_test/frontend_react/
    - name: Sleep for 2 minutes
      uses: jakejarvis/wait-action@master
      with:
        time: '2m'
    - name: FTP publish
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: pbr/
        localDir: First_test/frontend_react/build/
        options: "-v --delete"
